Make tester work

diff --git a/tests/runtests b/tests/runtests
--- a/tests/runtests
+++ b/tests/runtests
@@ -1,22 +1,21 @@
 #!/bin/bash
 
 echo "Running Tests"
-
 for dir in `ls -d */*/`;
 do
     cd $dir
     echo "Entering $dir"
     if ../../../bin/cilly --load=../../../lib/cil/inliner.cma \
-	    --load=../../../lib/cil/printers.cma --load=../../../lib/cil/cynthesis.cma \
-       	--docynthesis --cynthesis_print_flags=0 *.c
-    then 
-	   	for todo in `ls -d *.do`;
+        --load=../../../lib/cil/printers.cma --load=../../../lib/cil/cynthesis.cma \
+        --docynthesis --cynthesis_print_flags=0 *.c
+    then
+        for todo in `ls -d *.do`;
     	do
-	   		echo "Running $todo"
-    		vsim -c -do $todo | grep "SUCCESS\|FAILURE" || echo "ERROR"
+            echo "    Running $todo"
+            vsim -c -do "$todo" > tmp.out && grep "SUCCESS\|FAILED" tmp.out || echo "# ERROR"
     	done
-	else
-	    echo "# COMPILATION FAILURE"
-	fi
-	cd ../..
+    else
+        echo "# COMPILATION FAILURE"
+    fi
+    cd ../..
 done
